### ISSUE TITLE
Hook error

### ISSUE THREAD

**Issue by upperint** [Vanilla-OS/vanilla-system-operator#101]
When I try to install anything it gives error message:
E: Problem executing scripts DPkg::Post-Invoke '/usr/share/vso/hooks/apt-post'
E: Sub process returned an error code
Error: exit status 100
Usage: vso install [flags]
Flags: -h --help help for install

**Comment by upperint** [comment]
PS It doesn't export and for some reason Gnome Software won't load. Maybe it's connected or a plugin needs to be included

**Comment by taukakao** [comment]
This is now fixed but we can sadly not fix this bug in old images. You will have to adapt the /usr/share/vso/hooks/apt-post file yourself.
Here are the contents of the new file:
https://github.com/Vanilla-OS/vso-image/blob/main/includes.container/usr/share/vso/hooks/apt-post

You can also reinitialize the vso container but you will loose everything installed in there.
