### ISSUE TITLE
bug: desktop icons aren't exported for the sideloaded DEB packages

### ISSUE THREAD

**Issue by hozza** [Vanilla-OS/vanilla-system-operator#121]
Hey Vanilla OS devs!

Is there any documentation around how to use this Sideload utility? I'm testing Vanilla OS 2, downloaded Sublime Text 4 and 1Password as a `.deb` and Sideload was recomended as a way to install (since verified flatpaks are not available).

The installation seemed to complete successfully for both, however no desktop icon is visible in the menu and APX GUI shows no subsystems (unsure if that's related). Opening terminal and running "subl" opens the GUI ST4 application, not sure how to get 1Password opening .

Any idea what I'm doing wrong or is this intended?

Edit: removed "t" from `subtl`

**Comment by muhdsalm** [comment]
I'd like to be assigned to this. I've got it working and I've just got some cleanup left.
