### ISSUE TITLE
DNS doesn't match host settings

### ISSUE THREAD

**Issue by twihno** [Vanilla-OS/vanilla-system-operator#150]
The `resolv.conf` file inside the vso container doesn't match the the host's file.

This causes the unfortunate problem that e.g. DNS server set via a VPN connection don't work and the corresponding records cannot be resolved

**Comment by axtloss** [comment]
dupliacte of https://github.com/Vanilla-OS/vso-image/issues/42
we already came up with a fix, so it'll probably get fixed soon
