### ISSUE TITLE
VSO Update removes ABroot

### ISSUE THREAD

**Issue by tobehn** [Vanilla-OS/vanilla-system-operator#22]
When performing an Update via `sudo vso trigger-update --now` it runs the `apt update`, `apt upgrade` routine and asks for the reboot to make the transaction. 

After rebooting the `abroot` command is missing. VSO becomes version 1.2.0 (if i remember correctly)
Console gives and error: _Unknown command: abroot_

Triggering an update again via VSO leads to:

```
Triggering update now...
Smart update is disabled, skipping check.
An error occurred while trying to update the system.
    Please try again later and report the issue if it persists.

    ERR_CODE: %s CMD_TR_UP_NOW
Error: exec: "abroot": executable file not found in $PATH
```

VSO -v: 1.1.4
ABroot -v: 1.2.2

**Comment by mirkobrombin** [comment]
Check if vanilla-base-meta is installed. ABRoot depends on it

**Comment by tobehn** [comment]
Thanks for your response @mirkobrombin.

That was it. 
i did a `sudo abroot exec apt install vanilla-base-meta` 
and after the reboot i triggered the
`sudo vso trigger-update --now`.

the next reboot booted into a system including the `abroot` command.

though my updated versions are 

vso -v : 1.2.0
abroot -v : 1.2.2

I am pretty sure i installed from the second stable ISO-image after i had destroyed my first installation from the initial stable release. 


Bounty:
I think **vso** still claims to be version _1.2.0_ as you still have the variable set to "1.2.0" in _main.go_
Would love to create a PR whereas its easier if you update this file yourself. Becaus i also do not know if there are any other references or any other logic for the versioning.

**Comment by mirkobrombin** [comment]
I fix the version mismatch soon, thanks for reporting. I also added abroot as a vso dependency to prevent this behavior. I think apt had problems with the recent changes in the vanilla-base-meta package.

**Comment by tobehn** [comment]
Great, thank you very much. 

And btw. i really enjoy using vanillaOS and really like the concept. I was on Fedora Silverblue beforehand and do not want to miss immutability anymore. I think you hit it  by being ubuntu based, using vanilla gnome and making the whole system more configurable on the edges by creating the ABroot.

I follow closely and really want to contribute as much as possible.

Again, thanks a lot.

**Comment by mirkobrombin** [comment]
Thanks for the kind words <3
