### ISSUE TITLE
When Smart Update is disabled, the trigger update option doesn't work

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/vanilla-system-operator#24]
![Ref image 1](https://media.discordapp.net/attachments/1023245426385760267/1066233132396838932/image.png)
![Ref image 2](https://cdn.discordapp.com/attachments/1023245426385760267/1066279504198254612/image.png)

## Steps to replicate

- Disable SmartUpdate.
- Trigger an Update using vso.

## Error

When the `vso` update is triggered with smart update disabled nothing happens upon confirmation of the message.

cc @mirkobrombin

**Comment by mirkobrombin** [comment]
I figured it out. Looks like one of the latest ABRoot updates, breaks the `--assume-yes` flag. VSO should not even ask for confirmation.

**Comment by mirkobrombin** [comment]
fixed by https://github.com/Vanilla-OS/ABRoot/commit/1d35efa941d2c0523de469898e18fc1ba4c92d25
possible cause: https://github.com/Vanilla-OS/orchid/issues/13
