### ISSUE TITLE
Add an Update Indicator

### ISSUE THREAD

**Issue by MonsterObserver** [Vanilla-OS/vanilla-system-operator#31]
Many users reboot while an update is currently happening, we should make an indicator which shows them that an update is going on.

**Comment by mirkobrombin** [comment]
Adding some notes from an internal discussion: the notification should display a button to cancel it if the transaction is not in the final stages.

**Comment by taukakao** [comment]
I think having an Shutdown inhibitor might be useful here. 
When shutting down, the user would be notified that a program is inhibiting the shutdown.
The program should have a descriptive name to make clear that it's an upgrade.

**Comment by mirkobrombin** [comment]
Needs https://github.com/Vanilla-OS/ABRoot/issues/182

**Comment by mirkobrombin** [comment]
Closed by https://github.com/Vanilla-OS/vso-gnome-ext
