### ISSUE TITLE
Request: Make a Kernel upgrade utility for vso.

### ISSUE THREAD

**Issue by JMarcosHP** [Vanilla-OS/vanilla-system-operator#39]
I suggest to code a Kernel upgrade utility like Linux Mint or Manjaro Linux. To make the hardware config more easiest.

**Comment by mirkobrombin** [comment]
Thanks to Vib and ABRoot v2 supporting OCI images now, you'll be able to make your own vib image with a custom kernel and any other package/configuration you need.
