### ISSUE TITLE
VSO Always Exits With "exit status 1"

### ISSUE THREAD

**Issue by MonsterObserver** [Vanilla-OS/vanilla-system-operator#49]
This happens both when you run a binary, i.e. `vso run git`, and when you exit `vso shell`. The exact error is:

```sh
Error: exit status 1
Usage:
  vso shell [flags]
  
Flags:
  -h, --help   help for shell
  
  ERROR exit status 1

**Comment by matbme** [comment]
`vso run git` returns exit status 1 because the command itself returns this exit status when run bare. As for `vso shell` + `exit`, I can't reproduce the exit status. Is the latter still an issue?

**Comment by MonsterObserver** [comment]
> `vso run git` returns exit status 1 because the command itself returns this exit status when run bare. As for `vso shell` + `exit`, I can't reproduce the exit status. Is the latter still an issue?

If you cannot reproduce it I reckon it's fixed, I'll close the issue for now.
