### ISSUE TITLE
acpi battery checks don't account for multiple batteries

### ISSUE THREAD

**Issue by bketelsen** [Vanilla-OS/vanilla-system-operator#7]
my Surface Laptop 3 reports two batteries, one of which is probably a bug, but the other is valid and fully charged.

vso's acpi check doesn't account for multiple batteries, which are common in surface devices, and other laptops.

```root@vanilla:/etc/vso# acpi
Battery 0: Discharging, 0%, rate information unavailable
Battery 1: Full, 100%
root@vanilla:/etc/vso# 
```

**Comment by mirkobrombin** [comment]
I wonder if there is a more robust way of doing this check. Maybe reading directly from /sys

**Comment by bketelsen** [comment]
How about I write a go wrapper lib for `upower`?

**Comment by mirkobrombin** [comment]
This would be the perfect solution but will also take more time

**Comment by bketelsen** [comment]
but it would be my time, not yours :)
another option that would be faster is to read /sys/class/power_supply directly. That might be just an hour or two of work.

**Comment by bketelsen** [comment]
on second thought, this is too small for a useful package, I'll PR to this repo.
