### ISSUE TITLE
Preload the shell on login

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/vanilla-system-operator#77]
This will preload the shell (not init) at boot.

Requires: https://github.com/Vanilla-OS/apx/issues/314

Tasks:
- [ ] skip on a metered or poor connection
- [ ] implement a start command which starts the container if it exist
- [ ] create a systemd unit (or any other solution which runs on login) to execute that command

ref: https://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html

**Comment by taukakao** [comment]
I think this is implemented.

**Comment by mirkobrombin** [comment]
Yes it is!
