### ISSUE TITLE
Apx commands should run through the host shell instead of the vso container

### ISSUE THREAD

**Issue by shuriken1812** [Vanilla-OS/vanilla-system-operator#93]
In many scenarios in particular workflows it will be better to keep containers independent which was the case in vso v1. 
In my testing vso 2.0 seems to break some of this workflow let me explain with an example 

- You are using `tmux` which gets automatically invoked in your default vso container.
- Now you create more apx containers
- `tmux` gets called in those containers as well as you are auto invoking a tmux session
- So what happens is you invoke a tmux session inside a tmux session which ends up being a loop

This was not the case in in the alpha releases. As all the apx containers were invoked through the host shell.. so containers ran independent of each other despite having same config. Which in my opinion should be the better way otherwise this might conflict with many workflows. 

A good thing that can be done is that what apx command inside a vso container does is -> call the host-shell -> which will then invoke the apx container you are trying to enter and exits out of the vso container.

Example -

if you are in a vso-container -> `apx enter devbox` -> calls the `host-shell` to invoke the `apx enter devbox` command and exits the vso container -> devbox container is called from the `host-shell` which then runs as intended.

I can always do this myself in my configs to check if its an apx container then dont invoke tmux and other things, however this can be considered.

I hope i was able to explain the niche !

**Comment by taukakao** [comment]
This should be the case now.
If you run:
ls -l /usr/bin/apx
it should be a symlink to host-shell
